esphome:
  name: coffee-pot
esp8266:
  board: d1_mini


substitutions:
  $autoshutoff: "120min"  


wifi:
  ssid: IOTL
  password: !secret wifi_password
  reboot_timeout: 0s

api:
  reboot_timeout: 0s  
  password: !secret api_password
ota:  

script:
  - id: autoshutoff
    then:
      - delay: $autoshutoff
      - switch.turn_off: coffee_pot_heater
      - switch.turn_off: coffee_pot_light
      - script.execute: blink          

  - id: blink
    then:
      - script.execute: blink_repeat_1  
  - id: blink_repeat_1
    then:
      - switch.turn_off: coffee_pot_light
      - delay: 1s
      - switch.turn_on: coffee_pot_light
      - delay: 1s      
      - script.execute: blink_repeat_2
  - id: blink_repeat_2
    then:
      - switch.turn_off: coffee_pot_light
      - delay: 1s
      - switch.turn_on: coffee_pot_light
      - delay: 1s      
      - script.execute: blink_repeat_1   




binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    id: coffee_pot_switch
    name: Coffee Pot
    filters:
      - invert:  
    on_press:
      then:
       - switch.turn_on: coffee_pot_heater     
       - switch.turn_on: coffee_pot_light   
       - switch.turn_on: coffee_pot_safe          
       - script.execute: autoshutoff       
    on_release:
      then:
       - switch.turn_off: coffee_pot_heater
       - switch.turn_off: coffee_pot_safe       
       - switch.turn_off: coffee_pot_light 
       - switch.turn_off: coffee_pot_heater_helper        
       - script.stop: autoshutoff      
       - script.stop: blink       
       - script.stop: blink_repeat_1       
       - script.stop: blink_repeat_2                                       


switch:

  - platform: template
    name: Coffee Pot
    id: coffee_pot_heater_helper
    turn_on_action:
      - script.execute: autoshutoff  
      - delay: 1s
      - if: 
          condition:
              - binary_sensor.is_off: coffee_pot_switch   
              - switch.is_off: coffee_pot_safe
          then:
            - switch.turn_on: coffee_pot_heater 
            - switch.turn_on: coffee_pot_light    
            - delay: 1s
            - switch.turn_on: coffee_pot_safe       

  - platform: template
    id: coffee_pot_safe
    optimistic: true   

  - platform: gpio
    pin: D1
    id: coffee_pot_heater
    on_turn_off:
       - switch.turn_off: coffee_pot_light 
       - delay: 1s
       - script.stop: blink      

  - platform: gpio
    pin: D5
    id: coffee_pot_light
   
    
 